### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by jappyjan** [KodingDev/JetBrainsCopilot#2]
When hitting login,
my browser opens.
i accept the oauth request.
i get redirected.
i copy the callback url (which contains the "code" query argument)
i get the following error thrown in the ide (webstorm)

```
java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.CoroutineExceptionHandlerImplKt
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by d3ni00** [comment]
Same here.

**Comment by janhohenheim** [comment]
Might be because one now has to accept telemetry before usage? Did that change the authentication API?
